import { z } from "zod";

export const inquirySchema = z.object({
  parentName: z.string().min(2),
  childName: z.string().optional(),
  childAge: z.string().optional(),
  phone: z.string().min(10),
  email: z.string().email().optional().or(z.literal("")),
  message: z.string().max(1000).optional(),
  programSlug: z.string().optional(),
});

export const admissionSchema = z.object({
  fatherName: z.string().min(2),
  motherName: z.string().min(2),
  guardianName: z.string().optional().or(z.literal("")),
  primaryParent: z.enum(["FATHER", "MOTHER", "GUARDIAN"]),
  childName: z.string().min(2),
  childDob: z.string().min(1),
  fatherPhone: z.string().min(10).optional().or(z.literal("")),
  motherPhone: z.string().min(10).optional().or(z.literal("")),
  guardianPhone: z.string().optional().or(z.literal("")),
  fatherEmail: z.string().email().optional().or(z.literal("")),
  motherEmail: z.string().email().optional().or(z.literal("")),
  guardianEmail: z.string().email().optional().or(z.literal("")),
  fatherQualification: z.string().optional().or(z.literal("")),
  motherQualification: z.string().optional().or(z.literal("")),
  guardianQualification: z.string().optional().or(z.literal("")),
  fatherOccupation: z.string().optional().or(z.literal("")),
  motherOccupation: z.string().optional().or(z.literal("")),
  guardianOccupation: z.string().optional().or(z.literal("")),
  childAge: z.string().optional().or(z.literal("")),
  childGender: z.string().optional().or(z.literal("")),
  childBloodGroup: z.string().optional().or(z.literal("")),
  childAadhaar: z.string().optional().or(z.literal("")),
  preferredStartMonth: z.string().optional().or(z.literal("")),
  schoolVisitStatus: z.string().optional().or(z.literal("")),
  previousSchool: z.string().optional().or(z.literal("")),
  previousGrade: z.string().optional().or(z.literal("")),
  addressLine1: z.string().optional().or(z.literal("")),
  addressLine2: z.string().optional().or(z.literal("")),
  city: z.string().optional().or(z.literal("")),
  state: z.string().optional().or(z.literal("")),
  postalCode: z.string().optional().or(z.literal("")),
  emergencyContactName: z.string().optional().or(z.literal("")),
  emergencyContactPhone: z.string().optional().or(z.literal("")),
  emergencyRelationship: z.string().optional().or(z.literal("")),
  medicalNotes: z.string().max(2000).optional().or(z.literal("")),
  allergies: z.string().max(1000).optional().or(z.literal("")),
  parentExpectations: z.string().max(1000).optional().or(z.literal("")),
  notes: z.string().max(2000).optional(),
  programSlug: z.string().optional(),
});

export const contactSchema = z.object({
  name: z.string().min(2),
  email: z.string().email().optional().or(z.literal("")),
  phone: z.string().min(10).optional().or(z.literal("")),
  childAge: z.string().optional().or(z.literal("")),
  programInterest: z.string().optional().or(z.literal("")),
  preferredContactMethod: z.string().optional().or(z.literal("")),
  subject: z.string().min(2).optional().or(z.literal("")),
  message: z.string().min(10).max(2000),
});

export const visitBookingSchema = z.object({
  parentName: z.string().min(2),
  phone: z.string().min(10),
  email: z.string().email().optional().or(z.literal("")),
  childName: z.string().optional(),
  childAge: z.string().optional().or(z.literal("")),
  programInterest: z.string().optional().or(z.literal("")),
  preferredTimeSlot: z.string().optional().or(z.literal("")),
  visitDate: z.string().min(1),
  notes: z.string().max(1000).optional(),
});
